### ISSUE TITLE
invalid argument r.TrackerEvts for len()

### ISSUE THREAD

**Issue by Xeizzenauqzarr** [icza/s2prot#1]
invalid argument r.TrackerEvts (type *rep.TrackerEvts) for len

Basically, as I see it - no len() has been implemented for TrackerEvts.

**Comment by icza** [comment]
You're right. It was a slice in the past, and changed it to a `struct`. Will correct it.

**Comment by Xeizzenauqzarr** [comment]
**Update:**
I believe for the same reason it now throws this error when I try to iterate in a loop over it:
cannot range over r.TrackerEvts (type *rep.TrackerEvts)

**Comment by icza** [comment]
Fixed. To print the length (number) of tracker events and to iterate over them, you have to use the `TrackerEvts.Evts` field, like this:

	fmt.Printf("Tracker events: %d\n", len(r.TrackerEvts.Evts))

To iterate over them:

    for _, evt := range r.TrackerEvts.Evts {
        // Do something with evt:
        fmt.Println(evt)
    }

**Comment by Xeizzenauqzarr** [comment]
Ok, thank you.
