### ISSUE TITLE
Failed to parse replay: Decoding error

### ISSUE THREAD

**Issue by matthsims** [icza/s2prot#2]
I'm trying to use this package to decode the replays in the 3.16.1 [replay packages from Blizzard](https://github.com/Blizzard/s2client-proto#downloads). They are build 55958, but s2prot gives me "Failed to parse replay: Decoding error" whether I use your release version or a version I compiled myself (go 1.9.2). The output from version for each is:
```
$ ./s2prot -version
s2prot version: v1.2.0
Parser version: v1.2.0
Supported replay builds: 15405 .. 58400
Platform: linux amd64
Built with: go1.9.1
Author: Andras Belicza
Home page: https://github.com/icza/s2prot
```
And for the one I compiled:
```
$ ./s2prot -version
s2prot version: v1.2.0
Parser version: v1.2.0
Supported replay builds: 15405 .. 59587
Platform: linux amd64
Built with: go1.9.2
Author: Andras Belicza
Home page: https://github.com/icza/s2prot

$ git rev-parse --short HEAD
a51a640
```

Output:
```
$ ./s2prot -details /Replays/02/02096531b57da1ae35bc93ed37ac4b54eae3390d9753919e38cba94a93ca73fa.SC2Replay
Failed to parse replay: Decoding error
```
Note the flag doesn't matter, same output for any of -attrevts -details -gameevts -initdata -msgevts -trackerevts.

Any suggestions?

**Comment by icza** [comment]
Those replays are artificially altered to be anonymous. A lot of "important" detail is cut out of the replays which the parser depends on. See a similar issue with my other Scelight project: https://github.com/icza/scelight/issues/11

No ETA if and when these replays will be supported.

**Comment by icza** [comment]
Support for anonimized replays have been added, available at master. Will create a new binary release soon.
