### ISSUE TITLE
Unsupported replay version

### ISSUE THREAD

**Issue by lfaoro** [icza/s2prot#20]
hi @icza, thank you for creating this library.

I followed your examples, although I believe I'm doing something wrong as every file I try to open says:

```
2020/02/11 12:51:11 Unsupported replay version
2020/02/11 12:51:11 Unsupported replay version
2020/02/11 12:51:11 Unsupported replay version
2020/02/11 12:51:11 Unsupported replay version
2020/02/11 12:51:11 Unsupported replay version
2020/02/11 12:51:11 Unsupported replay version
2020/02/11 12:51:11 Unsupported replay version
2020/02/11 12:51:11 Unsupported replay version
2020/02/11 12:51:11 Unsupported replay version
2020/02/11 12:51:11 Unsupported replay version
2020/02/11 12:51:11 Unsupported replay version
2020/02/11 12:51:11 Unsupported replay version
```

code:

```
	err := filepath.Walk(scpath, func(path string, info os.FileInfo, err error) error {
		if !strings.Contains(path, "Multiplayer") &&
			!strings.Contains(info.Name(), ".SC2Replay") {
			return nil
		}

		replay, err := rep.NewFromFile(path)
		if err != nil {
			log.Println(err)
			return nil
		}
		defer replay.Close()
		fmt.Println(replay.Header.VersionString())

		return nil
	})
```

**Comment by icza** [comment]
What version of `s2prot` are you using? Please post the output of `s2prot -version`.

Also can you tell the version of the replays you try to parse?

**Comment by lfaoro** [comment]
Issue is with modules, if you do: `go get "github.com/icza/s2prot/rep"` it'll install an old version from your latest releases `s2prot v1.4.0`

To install the master version with your latest updates, one must do `go get github.com/icza/s2prot/rep@master `

**Comment by icza** [comment]
That's because latest additions were not yet released as a new version. That's to be expected.

**Comment by icza** [comment]
And I just now added the 2 newest protocol files for 4.10.4 and 4.11 reps.

**Comment by lfaoro** [comment]
awesome, meanwhile I updated the readme to avoid repeating issues like this
