### ISSUE TITLE
Command line utility is using old version

### ISSUE THREAD

**Issue by joshleblanc** [icza/s2prot#24]
```
PS C:\users\horiz\documents\dev\s2prot\cmd\s2prot> go build s2prot.go
go: finding github.com/icza/s2prot v1.4.0
go: downloading github.com/icza/s2prot v1.4.0
go: extracting github.com/icza/s2prot v1.4.0
go: finding github.com/icza/mpq latest
```

While the current version is 1.4.1

**Comment by icza** [comment]
The v1.4.1 is a "work-in-progress", it has not yet been released or tagged.

The last tagged and released version is v1.4.0, that's why that is downloaded.

If you need the latest commit, update it with:

    go get -u github.com/icza/s2prot@master

**Comment by joshleblanc** [comment]
I had actually run `go get -u github.com/icza/s2prot/rep@master` as mentioned in the readme before running the command I have in the original post, and it grabbed 1.4.0 anyway.

**Comment by icza** [comment]
Did you do that inside a module? Try the following:

- create a new, empty folder
- init a new module in it: `go mod init test`
- run the command `go get -u github.com/icza/s2prot@master`
- run `cat go.mod`

What do you see?

**Comment by joshleblanc** [comment]
Ahhh. running `go mod init s2prot` in the s2prot folder, then running `go get -u github.com/icza/s2prot@master` is not using the correct version.

Thanks!

**Comment by icza** [comment]
_"...is not using the correct version"_

You mean "...is **now** using the correct version", right?

**Comment by joshleblanc** [comment]
Yes!
