### ISSUE TITLE
Update to 4.1.2

### ISSUE THREAD

**Issue by tkiraly** [icza/s2prot#3]
Hi, can you update to the newsest version?

**Comment by icza** [comment]
The source code corresponds to the latest s2protocol, and supports the latest replay version.

Can you build a binary from the source? Or you're waiting for the binary release?

**Comment by tkiraly** [comment]
i tried your high level usage example and got an unsupported replay version error. 
my starcraft version is 4.1.2.
i attach the not working replay file:
[Blackpink LE (11).txt](https://github.com/icza/s2prot/files/1592755/Blackpink.LE.11.txt)

**Comment by icza** [comment]
Ok, I created binary releases for the latest version. You can view / download them here:

https://github.com/icza/s2prot/releases/tag/v1.3.0

Closing the issue.
