### ISSUE TITLE
Adding more supported replay versions? Contribution

### ISSUE THREAD

**Issue by Kaszanas** [icza/s2prot#36]
Hello,

My question is:
Is it possible to add more versions of SC2 replays to be supported and what are the potential problems with that?
I would be able to contribute in that regard as this is something I need.

I am currently using s2prot "rep" to be able to unpack some sc2 replay files.
I have run into the problem that is specified as:
```
Failed to open file: Unsupported replay version
```

EDIT:
This issue seems to be resolved when I updated the package but still let me know if there is anything to potentially improve in the package.

**Comment by icza** [comment]
`s2prot` relies on the protocol files published by Blizzard in the https://github.com/blizzard/s2protocol repo. Whenever they publish a new protocol file, it is integrated into this and thus replay versions "covered" by the new protocol file become supported.

**Comment by icza** [comment]
Currently all published protocol files are integrated. If you replays that are not supported, that means Blizzard have not published protocol files for them.

**Comment by Kaszanas** [comment]
Could it be that a replay ended in an instant disconnect and so it throws this error or would it be another one?
There are some SC2 games which end instantly after the game starts because of some kind of disruption.

**Comment by icza** [comment]
Not all protocols are published, Blizzard is a little lazy on that, and there may be internal or beta builds whose protocols are never published.
