### ISSUE TITLE
Details.MapFileName() returns an empty string

### ISSUE THREAD

**Issue by Kaszanas** [icza/s2prot#39]
During one of my tests performed on s2prot package I have found a problem that when I call:
```
details := replayData.Details
mapNameString := details.MapFileName()
```
This sample code returns an empty string. while the code below contains the map name e.g. "Cyber Forest LE":
```
details := replayData.Details
mapName := details.Struct["title"].(string)
```

Apart from this insight I also have a question.
Is there a way to have all of the map names translated to English if they come from a different game locale?

**Comment by icza** [comment]
To get the name of the map, use `Details.Title()`. `Details.MapFileName()` is not the map title, but as the name says, the name of the map file (if present).

There are no localized map titles saved in the replay. To get localized names, you have to open the map file which does contain localized names.

**Comment by Kaszanas** [comment]
Okay! Thank You, it seems a little misleading at first with the MapFileName() as I assumed that this is going to be the original map name too :)

Closing this.

**Comment by Kaszanas** [comment]
Is there any way to contact You outside of GitHub @icza ?

**Comment by icza** [comment]
You can find my email on this page: https://repmastered.app/about
