### ISSUE TITLE
Not consistent map coordinate information

### ISSUE THREAD

**Issue by Kaszanas** [icza/s2prot#42]
Dear Andras,

I know that this might be outside of the scope of Your knowledge.
While parsing with s2prot.rep I have noticed that ```initData.GameDescription``` contains ```MapSizeX``` and ```MapSizeY``` information like so

```
      "mapSizeX": 192,
      "mapSizeY": 208,
```

But when checking different events happening later on in different game events the information is not consistents and the values seem to be outside of the range like so:

```
    {
      "evtTypeName": "CmdUpdateTargetUnit",
      "id": 105,
      "loop": 196,
      "target": {
        "snapshotControlPlayerId": 0,
        "snapshotPoint": {
          "x": 159744,
          "y": 210944,
          "z": 49088
        },
        "snapshotUnitLink": 547,
        "snapshotUpkeepPlayerId": 0,
        "tag": 31195137,
        "targetUnitFlags": 111,
        "timer": 0
      },
      "userid": {
        "userId": 1
      }
    },
```

I am looking for cues on if there is any way to standardize this information.
If You have any knowledge in that regard I would greatly appreciate any help.

**Comment by icza** [comment]
Positions in commands and map size in `initData.GameDescription` are measured in different units.

Coordinates (`x`, `y` and `z`) in commands are integer numbers. To convert them to floating point locations, you have to divide them by `8192`.

For example:

    x = 159744 / 8192 = 19.5
    y = 210944 / 8192 = 25.75
    z = 49088 / 8192 = 5.9921865

**Comment by Kaszanas** [comment]
Thank You very much for providing this information ;)
I have incorporated it into my calculations.
I am closing this issue.
