### ISSUE TITLE
Missing binary for last update

### ISSUE THREAD

**Issue by crustamet** [icza/s2prot#43]
Hello i am trying to install s2prot on my shared hosting device, i am a little limited but i put last update

       https://github.com/icza/s2prot/releases/tag/v1.4.0

In this last release was for version up to 4.3.2

Starcraft 2 last update is : 5.0.7

Im sorry about this ticket but i have some replays in 2020

**Comment by icza** [comment]
I did not put up releases of the latest builds, but the source code contains support for all versions. Is it possible for you to build it from source?

**Comment by crustamet** [comment]
@icza no my shared hosting do not provide full access to build and compile stuff just basic PHP

**Comment by icza** [comment]
You do not need to build on the shared hosting server. Build it locally, on your computer, and upload use the result executable binary.

**Comment by icza** [comment]
Hmm. Wait, I create a new release.

**Comment by crustamet** [comment]
ok, i have never done that i will try :D i must install go lang right :D ?

**Comment by crustamet** [comment]
Thanks i really appreciate it :D

**Comment by icza** [comment]
There you go, released v1.5.0: https://github.com/icza/s2prot/releases

**Comment by crustamet** [comment]
Thanks really appreciate it.
