### ISSUE TITLE
Error: Unsupported replay version for multiple files

### ISSUE THREAD

**Issue by Kaszanas** [icza/s2prot#46]
Currently when attempting to process files from different StarCraft II tournaments such as:

- IEM Katowice 2022
- Dreamhack SC2 Masters Last Chance 2022
- TSL 8 (2021)
- Stay at HomeStory Cup 4 (2021)
- Dreamhack SC2 Masters Winter (2021)

The following error is logged: ```Unsupported replay version```.
My version of ```s2prot``` is: 
```
github.com/icza/mpq v0.0.0-20210726201956-250230d5a464 // indirect
github.com/icza/s2prot v1.5.0
```

This error affects whole replaypacks.
If there is anything that can be done to alleviate this issue, please let me know.

**Comment by icza** [comment]
There are commits afte the v1.5.0 tag, update to master using:

    go get -u github.com/icza/s2prot@master

Let me know if this fixes the replay parsing.

**Comment by Kaszanas** [comment]
@icza It seems to have fixed the problem.
I will verify once again later on and I will close this issue if I find that everything was processed correctly!
Thank you!

**Comment by Kaszanas** [comment]
Verified the errors once again and it seems that indeed the proposed solution works.

**Comment by icza** [comment]
Wanted to say I should mention this in the README, but it's already there:

> Install the latest version of the library:
>
>      go get -u github.com/icza/s2prot/rep@master

**Comment by Kaszanas** [comment]
@icza Yeah the issue is that I first installed the s2prot around 1-2 years ago so right now when updating via all of the usual golang commands it updated to the newest released version.
