### ISSUE TITLE
Game time calculation discrepancy

### ISSUE THREAD

**Issue by Kaszanas** [icza/s2prot#48]
Hello @icza 

While parsing the replays and looking for additional information over the internet,
I have found that every second of a replay should take 22.4 gameloops (on "faster" game mode).

I can see that your calculations assume that one second is 16 gameloops.
Could you provide some context for the parser calculations?

Reference: https://github.com/Blizzard/s2client-api/issues/164

**Comment by icza** [comment]
`s2prot` means to be a low level parsing library. It does not perform additional replay processing. The game length duration is just a convenient method.

Please note that my other open source project [Scelight](https://github.com/icza/scelight) provides comprehensive analysis and statistics calculation, including proper and configurable duration calculation.

**Comment by Kaszanas** [comment]
Thank you for the response, I assume that using gameloops is the most accurate way of checking the game time then and further calculations should be made based on the game speed that was used in the replay.

I am closing this.
