### ISSUE TITLE
Replay parser is localization-dependent

### ISSUE THREAD

**Issue by Xeizzen** [icza/s2prot#5]
Well, right now it is likely not false alarm because I checked this issue with multiple various replays and it turned out that replay parser can't get the names of the races if the names of these races were coded in different from english language, i.e. for example russian, like it is the case here:
```
&lt;XGOC&gt;Epsilan Solfender
45 45
Unknown Unknown
-v-
TODAY'S REPLAY
&lt;XGOC&gt;Epsilan Bobymayor
45 45
Unknown Unknown
-v-
TODAY'S REPLAY
&lt;XGOC&gt;Epsilan &lt;GoldM&gt;Sickneel
45 45
Unknown Unknown
-v-
TODAY'S REPLAY
&lt;XGOC&gt;Epsilan Solfender
45 45
Unknown Unknown
-v-
```

The code that could produce similar to this output:
```
matchup := r.Details.Matchup()
players := r.Details.Players()
for player := range players {
    fmt.Println(player.Name, player.Race().Letter, player.Race(), fmt.Println(matchup)
}
```

And the replay files that could help to localize the issue:
https://www.dropbox.com/s/hnclzxxp568lfph/Multiplayer.rar?dl=1

And perhaps you can generate the replay files with various localizations yourself since you can instal any of the localizations the starcraft is supplied with.

**Comment by icza** [comment]
You are right. s2prot has built-in localized race name detection, but these replays contains a variant for the Russian races, e.g. s2prot recognized `"Терран"` as Terran, but these replays contain `"Терраны"` for Terran.

Added these new Russian race name variants, they should be handled properly. Thanks for reporting it.
