### ISSUE TITLE
switch over rep.Result

### ISSUE THREAD

**Issue by Xeizzen** [icza/s2prot#6]
Is it possible to switch over the Result?
Like that, for example:
```
switch player.Result() {
case rep.Result.Victory:
	fmt.Println("Victory")
case rep.Result.Defeat:
	fmt.Println("Defeat")
default:
	fmt.Println("Something else")
}
```

**Comment by icza** [comment]
Yes, [`Player.Result()`](https://godoc.org/github.com/icza/s2prot/rep#Player.Result) returns an enum-like pointer type [`rep.Result`](https://godoc.org/github.com/icza/s2prot/rep#Result), which is comparable.

The possible values are listed in the [Variables](https://godoc.org/github.com/icza/s2prot/rep#pkg-variables) section. The valid code is:

```
switch player.Result() {
case rep.ResultVictory:
	fmt.Println("Victory")
case rep.ResultDefeat:
	fmt.Println("Defeat")
case rep.ResultTie:
	fmt.Println("Tie")
default:
	fmt.Println("Unknown")
}
```

**Comment by Xeizzen** [comment]
Thank you.
