### ISSUE TITLE
New update for SC2 is released

### ISSUE THREAD

**Issue by Xeizzen** [icza/s2prot#7]
A new update for SC2 is released with a new update for replay parser protocol: https://github.com/Blizzard/s2protocol/blob/master/s2protocol/versions/protocol62848.py

Is there a possibility to get an update to match this new protocol definition?
And is it possible to automate the process?

**Comment by icza** [comment]
Yes, will add the new protocol soon. Making it automatic is not so simple.

**Comment by icza** [comment]
Done, see a566ae957248cadf27f359d2015f62f514e5e240.

**Comment by Xeizzen** [comment]
Thank you.
And it duplicates the definition? Seriously? After the changes they've made?
I'm surprised, the only I can tell.
